version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ps_thakker_e_commerce
    ports:
      - "8000:8000"
    volumes:
      - .:/E-commerce
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"
      DB_NAME: e_commerce
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    entrypoint: ["/E-commerce/entrypoint.sh"]  # Custom startup script 

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: e_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d e_commerce"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
