# Generated by Django 5.0.3 on 2024-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tandc',
            field=models.TextField(blank=True),
        ),
    ]
