# Generated by Django 5.0.3 on 2024-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customuser_tandc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tandc',
            field=models.CharField(blank=True),
        ),
    ]
