# Generated by Django 4.2.11 on 2024-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customuser_tandc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='old_cart',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
