# Generated by Django 4.2.11 on 2024-03-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customuser_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='old_wishlist',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
