# Generated by Django 4.2.11 on 2024-04-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_order_shipping_address'),
        ('customer', '0005_customuser_old_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.shippingaddressmodel'),
        ),
    ]
