# Generated by Django 4.2.11 on 2024-04-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='shipping_address',
        ),
    ]
