# Generated by Django 4.2.11 on 2024-03-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
