# Generated by Django 4.2.11 on 2024-04-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddressmodel',
            old_name='shipping_address_line_1',
            new_name='shipping_address',
        ),
    ]
