# Generated by Django 4.2.11 on 2024-04-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_rename_shipping_address_line_1_shippingaddressmodel_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='user_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')]),
        ),
    ]
