# Generated by Django 4.2.11 on 2024-04-03 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_order_order_number_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
