# Generated by Django 4.2.11 on 2024-04-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_orderitems_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='total_price',
        ),
    ]
