# Generated by Django 4.2.11 on 2024-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_orderitems_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
