# Generated by Django 4.2.11 on 2024-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_orderitems_img_orderitems_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
